### PR TITLE
update the todo

### PR DESCRIPTION
**Pull request by sadwxqezc**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hey @sadwxqezc, thanks a lot for contributing! I'm not going to merge this quite yet, because I feel like this makes the experience a whole lot more complicated.

One of things you've added is a `-a` flag for adding items, moving the "to do list" functionality back into the `todo` command. I hesitate with this, because I'd like to keep adding tasks as simple as possible. Additionally, it adds the date, which I feel clutters up the desktop (and that information can be shown with <kbd>Cmd-I</kbd>). The other thing is the `-r` flag, whose functionality is already present in the `todone` script.

What I'm trying to get at is asking, does this extra complication (using flags instead of different commands) _help_ someone using this script? Personally, I find typing `todo buy milk` easier than `todo -a buy milk` and `todone buy milk` easier than `todo -r buy milk`. It's more characters, and definitely more thought. Do you see what I mean? What's your reaction?

**Comment by sadwxqezc** [comment]
Hi @lachlanjc , in fact I'm trying to develop a fully functional `todo` cmd. I use `todo buy milk` and `todo -a buy milk` again, it's true than `todo, to do list, todone` feels simpler than `todo` with multiple flags.  But I still need functions like `categories`,`levels`,`notifications` in `todo`, and when there are more functions, `todo, todolist, todone` may still need extra flags, do you have any good idea in keeping `todo, to do list, todone` simple in this situation?

**Comment by lachlanjc** [comment]
Interesting. I'd like to keep the scope of this project very simple (with the separate commands), but it's fantastic if you'd like to write all that! (though you can use OS X Tags for categories)

Instead of adding all those features to this project, I'd recommend adding them to your fork. Once you're ready with some of the extra features, just send me a line and I'll add a link to my README! That way people can choose whether they want something super simple or more complex. Sound good?

**Comment by sadwxqezc** [comment]
Excellent!

**Pull request closed without merging**
